[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
my-project = "my_project.main:main"
my-calculator = "my_project.calculator:calculator"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 